public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    NUMBER_LITERAL,
    STRING_LITERAL,
    CHARACTER_LITERAL,
    OPERATOR,
    SEPARATOR,
    DELIMITER,
    COMMENT,
    PREPROCESSOR_DIRECTIVE
}